// project-docs/src/server.js
const express = require('express');
const path = require('path');
const fs = require('fs');

const { ROOT, ensureDirs } = require('./paths');
const { readDoc } = require('./files');
const docsRouter = require('./routes/docs');
const todosRouter = require('./routes/todos');
const ticketsRouter = require('./routes/tickets');

ensureDirs();

const app = express();
const PORT = process.env.PORT || 4500;
const TITLE = process.env.DOCS_TITLE || path.basename(ROOT) || 'Project Docs';
const TMPL = path.join(__dirname, 'template.html');

app.use(express.json({ limit: '10mb' }));
app.use(express.static(path.join(__dirname, '../public')));
app.use('/api/doc', docsRouter);
app.use('/api/todos', todosRouter);
app.use('/api/tickets', ticketsRouter);

// ── Config API ───────────────────────────────────────────────────────────────
app.get('/api/config', (_req, res) => {
  res.json({ title: TITLE, port: String(PORT), root: ROOT });
});

// ── Views ─────────────────────────────────────────────────────────────────────
const VIEWS = ['workflow', 'diagram', 'architecture', 'tickets'];
function title() { return TITLE; }

// Landing: empty-state idea capture until workflow.md exists, then Workflow.
app.get('/', (_req, res) => {
  if (readDoc('workflow').exists) return res.redirect('/workflow');
  res.send(renderEditorView({
    view: 'idea', label: 'Idea', docName: 'idea', writable: true, active: null,
    heading: 'Capture your idea',
    hint: 'Describe the app or feature you’re about to build. Save it, then ask Claude Code to populate the Workflow and Diagram views.',
    afterSaveHint: 'Saved to docs/idea.md. Now ask Claude Code to populate the Workflow and Diagram views.',
    centered: true,
  }));
});

app.get('/idea', (_req, res) => {
  res.send(renderEditorView({
    view: 'idea', label: 'Idea', docName: 'idea', writable: true, active: null,
    heading: 'Idea', hint: 'Your initial idea capture (docs/idea.md).',
    afterSaveHint: 'Saved to docs/idea.md.', centered: true,
  }));
});

app.get('/workflow', (_req, res) => {
  res.send(renderEditorView({
    view: 'workflow', label: 'Workflow', docName: 'workflow', writable: true, active: 'workflow',
    heading: 'Workflow',
    hint: 'How this app / feature should work. Editable — saved to docs/workflow.md.',
    afterSaveHint: 'Saved to docs/workflow.md.', centered: false,
  }));
});

// Architecture — read-only render of docs/architecture.md with an auto-TOC.
app.get('/architecture', (_req, res) => {
  const content = `
  <section class="doc-layout" data-view="architecture">
    <aside class="toc"><div class="toc-label">On this page</div><nav id="arch-toc"></nav></aside>
    <div class="doc-main">
      <header class="view-head">
        <h1>Architecture</h1>
        <p class="view-hint">Read-only — Claude Code maintains <code>docs/architecture.md</code>.</p>
      </header>
      <div id="arch-empty" class="empty-state" hidden>
        <p><strong>No architecture doc yet.</strong></p>
        <p>Ask Claude Code to write <code>docs/architecture.md</code> describing the system.</p>
      </div>
      <div id="viewer" class="doc-viewer"></div>
    </div>
  </section>`;
  const headExtra = `<script src="https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.min.js"></script>`;
  res.send(shell({ viewLabel: 'Architecture', active: 'architecture', content, pd: { view: 'architecture', docName: 'architecture' }, headExtra }));
});

// Diagram — read-only Mermaid render of docs/diagram.mmd (not seeded).
app.get('/diagram', (_req, res) => {
  const content = `
  <section class="diagram-view" data-view="diagram">
    <header class="view-head">
      <h1>Diagram</h1>
      <p class="view-hint">Read-only — generated by Claude Code from your idea &amp; workflow.</p>
      <span id="diagram-mtime" class="view-meta"></span>
    </header>
    <div id="diagram-empty" class="empty-state" hidden>
      <p><strong>No diagram yet.</strong></p>
      <p>Ask Claude Code to generate one (general components first) into <code>docs/diagram.mmd</code>.</p>
    </div>
    <div id="diagram-error" class="diagram-error" hidden></div>
    <div id="diagram-render" class="diagram-render"></div>
  </section>`;
  const headExtra = `<script src="https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.min.js"></script>`;
  res.send(shell({ viewLabel: 'Diagram', active: 'diagram', content, pd: { view: 'diagram', docName: 'diagram' }, headExtra }));
});

// Tickets — grid + detail modal + Todo panel.
app.get('/tickets', (_req, res) => {
  const content = `
  <section class="tickets-view" data-view="tickets">
    <header class="view-head tickets-head">
      <div>
        <h1>Tickets</h1>
        <p class="view-hint">Each ticket is a file in <code>tasks/</code>. Write what you want built; Claude Code implements open ones.</p>
      </div>
      <button id="new-ticket-btn" class="btn-primary">New ticket</button>
    </header>
    <div id="tickets-grid" class="tickets-grid"><p class="muted">Loading…</p></div>
  </section>

  <div id="ticket-modal" class="modal-overlay hidden">
    <div class="modal-box">
      <div class="modal-head">
        <input id="m-title" class="m-title" placeholder="Ticket title" />
        <span id="m-status" class="status-chip"></span>
        <button id="m-close" class="icon-btn" title="Close">×</button>
      </div>
      <label class="field-label">Reasoning</label>
      <textarea id="m-reasoning" class="m-reasoning" rows="2" placeholder="Why this ticket exists…"></textarea>
      <label class="field-label">Steps</label>
      <ul id="m-steps" class="m-steps"></ul>
      <div class="m-step-add">
        <input id="m-step-input" placeholder="Add a step…" />
        <button id="m-step-add-btn" class="btn-ghost">Add step</button>
      </div>
      <label class="field-label">Instructions for Claude Code <span class="muted">(saved to the task file)</span></label>
      <div id="m-body"></div>
      <div class="modal-actions">
        <span id="m-status-msg" class="save-status"></span>
        <button id="m-toggle" class="btn-ghost"></button>
        <button id="m-delete" class="btn-danger">Delete</button>
        <button id="m-save" class="btn-primary">Save</button>
      </div>
    </div>
  </div>`;
  res.send(shell({ viewLabel: 'Tickets', active: 'tickets', content, pd: { view: 'tickets' } }));
});

// ── Page assembly ───────────────────────────────────────────────────────────
function navLinks(active) {
  return VIEWS.map(v => {
    const label = v[0].toUpperCase() + v.slice(1);
    const cls = v === active ? ' class="nav-active"' : '';
    return `<a href="/${v}"${cls}>${label}</a>`;
  }).join('\n      ');
}

// Global Todo/Tickets panel — shown on every view EXCEPT Tickets (redundant there).
function rightPanelHtml() {
  return `<button id="right-open" class="right-open-btn" title="Open Todo panel">☰ Todo</button>
    <aside id="right-panel">
      <div class="rp-header">
        <div class="rp-tabs">
          <button class="rp-tab active" data-tab="todos">Todo</button>
          <button class="rp-tab" data-tab="tickets">Tickets</button>
        </div>
        <button id="right-close" class="rp-close-btn" title="Close">×</button>
      </div>
      <div id="rp-todos" class="rp-pane active">
        <div class="todo-add">
          <textarea id="todo-input" rows="2" placeholder="Add a todo…  (Enter to add · Shift+Enter for a new line)"></textarea>
          <button id="todo-add-btn" class="btn-primary">Add</button>
        </div>
        <ul id="todo-list"></ul>
      </div>
      <div id="rp-tickets" class="rp-pane">
        <ul id="ticket-list"></ul>
      </div>
    </aside>`;
}

function shell({ viewLabel, active, content, pd, headExtra = '' }) {
  const tmpl = fs.readFileSync(TMPL, 'utf8');
  const rightPanel = active === 'tickets' ? '' : rightPanelHtml();
  return tmpl
    .replace(/\{\{TITLE\}\}/g, esc(title()))
    .replace('{{VIEW_LABEL}}', esc(viewLabel))
    .replace('{{HEAD_EXTRA}}', headExtra)
    .replace('{{NAV_LINKS}}', navLinks(active))
    .replace('{{CONTENT}}', content)
    .replace('{{RIGHT_PANEL}}', rightPanel)
    .replace('{{PD_JSON}}', JSON.stringify(pd));
}

function renderEditorView(o) {
  const content = `
  <section class="editor-view${o.centered ? ' centered' : ''}" data-view="${o.view}">
    <header class="view-head">
      <h1>${esc(o.heading)}</h1>
      <p class="view-hint">${esc(o.hint)}</p>
    </header>
    <div id="editor"></div>
    <div class="editor-actions">
      <span id="save-status" class="save-status"></span>
      <button id="save-btn" class="btn-primary">Save</button>
    </div>
  </section>`;
  return shell({
    viewLabel: o.label, active: o.active, content,
    pd: { view: o.view, docName: o.docName, writable: o.writable, afterSaveHint: o.afterSaveHint },
  });
}

function esc(s) {
  return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

app.listen(PORT, () => {
  console.log(`Project Docs → http://localhost:${PORT}`);
  console.log(`Project root  → ${ROOT}`);
});
