// project-docs/src/server.js
const express = require('express');
const path = require('path');
const fs = require('fs');

const { ROOT, REQUESTS_DIR, PLANS_DIR, REPORTS_DIR, ensureDirs } = require('./paths');
const { readDoc } = require('./files');
const docsRouter = require('./routes/docs');
const collectionRouter = require('./routes/collection');

ensureDirs();

const app = express();
const PORT = process.env.PORT || 4500;
const TITLE = process.env.DOCS_TITLE || path.basename(ROOT) || 'Project Docs';
const TMPL = path.join(__dirname, 'template.html');

app.use(express.json({ limit: '10mb' }));
app.use(express.static(path.join(__dirname, '../public')));
app.use('/api/doc', docsRouter);
app.use('/api/requests', collectionRouter(REQUESTS_DIR, { writable: true }));
app.use('/api/plans', collectionRouter(PLANS_DIR));
app.use('/api/reports', collectionRouter(REPORTS_DIR));

// ── Config API ───────────────────────────────────────────────────────────────
app.get('/api/config', (_req, res) => {
  res.json({ title: TITLE, port: String(PORT), root: ROOT });
});

// ── Views ─────────────────────────────────────────────────────────────────────
const VIEWS = ['workflow', 'diagram', 'architecture', 'requests', 'plans', 'reports'];
function title() { return TITLE; }

// Landing: empty-state idea capture until workflow.md exists, then Workflow.
app.get('/', (_req, res) => {
  if (readDoc('workflow').exists) return res.redirect('/workflow');
  res.send(renderEditorView({
    view: 'idea', label: 'Idea', docName: 'idea', writable: true, active: null,
    heading: 'Capture your idea',
    hint: 'Describe the app or feature you’re about to build. Save it, then ask Claude Code to populate the Workflow and Diagram views.',
    afterSaveHint: 'Saved to docs/idea.md. Now ask Claude Code to populate the Workflow and Diagram views.',
    centered: true,
  }));
});

app.get('/idea', (_req, res) => {
  res.send(renderEditorView({
    view: 'idea', label: 'Idea', docName: 'idea', writable: true, active: null,
    heading: 'Idea', hint: 'Your initial idea capture (docs/idea.md).',
    afterSaveHint: 'Saved to docs/idea.md.', centered: true,
  }));
});

app.get('/workflow', (_req, res) => {
  res.send(renderEditorView({
    view: 'workflow', label: 'Workflow', docName: 'workflow', writable: true, active: 'workflow',
    heading: 'Workflow',
    hint: 'How this app / feature should work. Editable — saved to docs/workflow.md.',
    afterSaveHint: 'Saved to docs/workflow.md.', centered: false,
  }));
});

// Architecture — read-only render of docs/architecture.md with an auto-TOC.
app.get('/architecture', (_req, res) => {
  const content = `
  <section class="doc-layout" data-view="architecture">
    <aside class="toc"><div class="toc-label">On this page</div><nav id="arch-toc"></nav></aside>
    <div class="doc-main">
      <header class="view-head">
        <h1>Architecture</h1>
        <p class="view-hint">Read-only — Claude Code maintains <code>docs/architecture.md</code>.</p>
      </header>
      <div id="arch-empty" class="empty-state" hidden>
        <p><strong>No architecture doc yet.</strong></p>
        <p>Ask Claude Code to write <code>docs/architecture.md</code> describing the system.</p>
      </div>
      <div id="viewer" class="doc-viewer"></div>
    </div>
  </section>`;
  res.send(shell({ viewLabel: 'Architecture', active: 'architecture', content, pd: { view: 'architecture', docName: 'architecture' }, headExtra: MERMAID }));
});

// Diagram — read-only Mermaid render of docs/diagram.mmd (not seeded).
app.get('/diagram', (_req, res) => {
  const content = `
  <section class="diagram-view" data-view="diagram">
    <header class="view-head">
      <h1>Diagram</h1>
      <p class="view-hint">Read-only — generated by Claude Code from your idea &amp; workflow.</p>
      <span id="diagram-mtime" class="view-meta"></span>
    </header>
    <div id="diagram-empty" class="empty-state" hidden>
      <p><strong>No diagram yet.</strong></p>
      <p>Ask Claude Code to generate one (general components first) into <code>docs/diagram.mmd</code>.</p>
    </div>
    <div id="diagram-error" class="diagram-error" hidden></div>
    <div id="diagram-render" class="diagram-render"></div>
  </section>`;
  res.send(shell({ viewLabel: 'Diagram', active: 'diagram', content, pd: { view: 'diagram', docName: 'diagram' }, headExtra: MERMAID }));
});

// ── Collections: Requests / Plans / Reports (index + reader) ─────────────────
const COLLECTIONS = {
  requests: {
    label: 'Requests',
    hint: 'What you want built or changed — written in the composer (✎, bottom right), saved to <code>docs/requests/</code>. Ask Claude Code to turn a request into a plan.',
    empty: `<p><strong>No requests yet.</strong></p>
            <p>Open the composer with the <strong>✎ New request</strong> button (any view) and write what you want.</p>`,
  },
  plans: {
    label: 'Plans',
    hint: 'Claude Code’s implementation plans — current state, the change &amp; why, step-by-step, test suite, and before/after diagrams. Read-only; files live in <code>docs/plans/</code>.',
    empty: `<p><strong>No plans yet.</strong></p>
            <p>Write a request, then ask Claude Code: <em>“draft a plan for request …”</em> — it writes the plan here.</p>`,
  },
  reports: {
    label: 'Reports',
    hint: 'Work reports written when a task is finished — what was done, the reasoning, and how the data flows. Read-only; files live in <code>docs/reports/</code>.',
    empty: `<p><strong>No reports yet.</strong></p>
            <p>When Claude Code (or any AI) finishes a piece of work, it writes a report to <code>docs/reports/</code>.</p>`,
  },
};

for (const [view, c] of Object.entries(COLLECTIONS)) {
  app.get('/' + view, (_req, res) => {
    const content = `
  <section class="col-view" data-view="${view}">
    <header class="view-head">
      <h1>${c.label}</h1>
      <p class="view-hint">${c.hint}</p>
    </header>
    <div id="col-empty" class="empty-state" hidden>${c.empty}</div>
    <div id="col-index" class="reports-index"><p class="muted">Loading…</p></div>
  </section>

  <section class="doc-layout" id="col-reader" hidden>
    <aside class="toc"><div class="toc-label">On this page</div><nav id="arch-toc"></nav></aside>
    <div class="doc-main">
      <header class="view-head report-head">
        <a href="/${view}" class="btn-ghost report-back">← All ${view}</a>
        <div id="col-meta"></div>
      </header>
      <div id="viewer" class="doc-viewer"></div>
    </div>
  </section>`;
    res.send(shell({ viewLabel: c.label, active: view, content, pd: { view, colApi: '/api/' + view, colLabel: c.label }, headExtra: MERMAID }));
  });
}

// The retired Tickets view → Requests.
app.get('/tickets', (_req, res) => res.redirect('/requests'));

// ── Page assembly ───────────────────────────────────────────────────────────
const MERMAID = `<script src="https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.min.js"></script>`;

function navLinks(active) {
  return VIEWS.map(v => {
    const label = v[0].toUpperCase() + v.slice(1);
    const cls = v === active ? ' class="nav-active"' : '';
    return `<a href="/${v}"${cls}>${label}</a>`;
  }).join('\n      ');
}

// Global Request composer — a wide slide-in panel, available on every view.
function composerHtml() {
  return `<button id="composer-open" class="composer-open-btn" title="Write a new request">✎ New request</button>
    <aside id="composer">
      <div class="composer-head">
        <div>
          <div class="composer-title">New request</div>
          <div class="composer-hint">Brainstorm freely — saved to <code>docs/requests/</code>, then ask Claude Code for a plan.</div>
        </div>
        <button id="composer-close" class="rp-close-btn" title="Close">×</button>
      </div>
      <div id="composer-editor"></div>
      <div class="composer-actions">
        <span id="composer-status" class="save-status"></span>
        <button id="composer-save" class="btn-primary">Save request</button>
      </div>
    </aside>`;
}

function shell({ viewLabel, active, content, pd, headExtra = '' }) {
  const tmpl = fs.readFileSync(TMPL, 'utf8');
  return tmpl
    .replace(/\{\{TITLE\}\}/g, esc(title()))
    .replace('{{VIEW_LABEL}}', esc(viewLabel))
    .replace('{{HEAD_EXTRA}}', headExtra)
    .replace('{{NAV_LINKS}}', navLinks(active))
    .replace('{{CONTENT}}', content)
    .replace('{{RIGHT_PANEL}}', composerHtml())
    .replace('{{PD_JSON}}', JSON.stringify(pd));
}

function renderEditorView(o) {
  const content = `
  <section class="editor-view${o.centered ? ' centered' : ''}" data-view="${o.view}">
    <header class="view-head">
      <h1>${esc(o.heading)}</h1>
      <p class="view-hint">${esc(o.hint)}</p>
    </header>
    <div id="editor"></div>
    <div class="editor-actions">
      <span id="save-status" class="save-status"></span>
      <button id="save-btn" class="btn-primary">Save</button>
    </div>
  </section>`;
  return shell({
    viewLabel: o.label, active: o.active, content,
    pd: { view: o.view, docName: o.docName, writable: o.writable, afterSaveHint: o.afterSaveHint },
  });
}

function esc(s) {
  return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

app.listen(PORT, () => {
  console.log(`Project Docs → http://localhost:${PORT}`);
  console.log(`Project root  → ${ROOT}`);
});
